### ISSUE TITLE
Display not working with IS_WEMOS

### ISSUE THREAD

**Issue by delboy711** [rin67630/Drok-Juntek-on-steroids#1]
Just trying out this project. First problem found was no output on my Oled display when using the IS_WEMOS option.

Problem traced to b_Functions.ino  the declaration for display has the SDA and SCL parameters the wrong way around

`#ifdef CONTR_IS_WEMOS`
`SSD1306Wire display(0x3c, I2C_SCL, I2C_SDA);                  //OLED 128*64 soldered`
`#endif`

should be 
`SSD1306Wire display(0x3c, I2C_SDA, I2C_SCL);`

The only other issue I have had is with the library paths. The Arduino IDE does not find the libraries  unless I set the relative path such as
`#include "libraries/SoftPower_HAL_Files/FLA12-100Ah.h"`

At the moment I do not have access to a power module to test it out with.  I have ordered a new BST900 to try it with.

**Comment by rin67630** [comment]
It is apparently dependent on the board you use: 
With the Wemos OLED, I had it needed the 
`SSD1306Wire display(0x3c, I2C_SCL, I2C_SDA); `
in that way.
If you don't have any hardware (excepted a naked Wemos)  you should use the options 
#define ADC_IS_SIMULATED    
#define CONV_IS_SIMULATED

You need also valid credentials at Thinger.io and to have defined a device there that matches DEVICE_NAME.
Else commnet out the
#define THINGER line.
